name: bm2_text_audio_app
description: App to listen and read English Texts with Audios

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  audioplayers: ^0.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0

#launcher icons
flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/icon/icon_ios.png
  image_path_android: assets/icon/icon_android.png
  adaptive_icon_background: assets/icon/icon_backgroud.png
  adaptive_icon_foreground: assets/icon/icon_foregroud.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.png
    - assets/audios/1/jake.mp3
    - assets/audios/1/john.mp3
    - assets/audios/1/moira.mp3
    - assets/audios/1/natalie.mp3
    - assets/audios/2/jake.mp3
    - assets/audios/2/john.mp3
    - assets/audios/2/moira.mp3
    - assets/audios/2/natalie.mp3
    - assets/audios/3/jake.mp3
    - assets/audios/3/john.mp3
    - assets/audios/3/moira.mp3
    - assets/audios/3/natalie.mp3
    - assets/audios/4/jake.mp3
    - assets/audios/4/john.mp3
    - assets/audios/4/moira.mp3
    - assets/audios/4/natalie.mp3
    - assets/audios/5/jake.mp3
    - assets/audios/5/john.mp3
    - assets/audios/5/moira.mp3
    - assets/audios/5/natalie.mp3
    - assets/audios/6/jake.mp3
    - assets/audios/6/john.mp3
    - assets/audios/6/moira.mp3
    - assets/audios/6/natalie.mp3
    - assets/audios/7/jake.mp3
    - assets/audios/7/john.mp3
    - assets/audios/7/moira.mp3
    - assets/audios/7/natalie.mp3
    - assets/audios/8/jake.mp3
    - assets/audios/8/john.mp3
    - assets/audios/8/moira.mp3
    - assets/audios/8/natalie.mp3
    - assets/audios/9/jake.mp3
    - assets/audios/9/john.mp3
    - assets/audios/9/moira.mp3
    - assets/audios/9/natalie.mp3
    - assets/audios/10/jake.mp3
    - assets/audios/10/john.mp3
    - assets/audios/10/moira.mp3
    - assets/audios/10/natalie.mp3
    - assets/audios/11/1.mp3
    - assets/audios/11/2.mp3
    - assets/audios/11/3.mp3
    - assets/audios/11/4.mp3
    - assets/audios/11/5.mp3
    - assets/audios/11/6.mp3
    - assets/audios/11/7.mp3
    - assets/audios/11/full.mp3
    - assets/sentences/isp-01.mp3
    - assets/sentences/isp-02.mp3
    - assets/sentences/isp-03.mp3
    - assets/sentences/isp-04.mp3
    - assets/sentences/isp-05.mp3
    - assets/sentences/isp-06.mp3
    - assets/sentences/isp-07.mp3
    - assets/sentences/isp-08.mp3
    - assets/sentences/isp-09.mp3
    - assets/sentences/isp-10.mp3
    - assets/sentences/isp-11.mp3
    - assets/sentences/isp-12.mp3
    - assets/sentences/isp-13.mp3
    - assets/sentences/isp-14.mp3
    - assets/sentences/isp-15.mp3
    - assets/sentences/isp-16.mp3
    - assets/sentences/isp-17.mp3
    - assets/sentences/isp-18.mp3
    - assets/sentences/isp-19.mp3
    - assets/sentences/isp-20.mp3
    - assets/pronunciations/m1.mp3
    - assets/pronunciations/f1.mp3
    - assets/pronunciations/f2.mp3
    - assets/pronunciations/m3.mp3
    - assets/pronunciations/f3.mp3
    - assets/pronunciations/f4.mp3
    - assets/pronunciations/m4.mp3
    - assets/pronunciations/f5.mp3
    - assets/pronunciations/f6.mp3
    - assets/pronunciations/m6.mp3


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
